services:
  valhalla:
    image: ghcr.io/valhalla/valhalla:3.6.2
    container_name: floodmap-valhalla-hanoi
    command: ["valhalla_service", "/custom_files/valhalla.json", "2"]
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files:/custom_files
    environment:
      use_tiles_ignore_pbf: "False"
      server_threads: "2"
    restart: unless-stopped
